version: "3.8"

networks:
  my_network:
    driver: bridge

services:
  postgres:
    networks:
      - my_network
    image: postgres:latest
    container_name: doflamingo_database
    environment:
      POSTGRES_DB: doflamingo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 393406
    ports:
      - "5436:5432"
    volumes:
      - db:/var/lib/postgresql/data

  doflamingo:
    networks:
      - my_network
    build:
      context: .
      dockerfile: Dockerfile
    container_name: doflamingo
    ports:
      - 8080:8080
    volumes:
      - .:/app
    depends_on:
      - postgres

  grafana:
    networks:
      - my_network
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    restart: unless-stopped
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - grafana-data:/var/lib/grafana
      
  prometheus:
    networks:
      - my_network
    image: prom/prometheus:latest
    container_name: Prometheus-flamingo
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  loki:
    image: grafana/loki:2.9.2
    container_name: loki-flamingo
    ports:
      - "3100:3100"
    volumes: 
      - /home/umut/Doflamingo/loki-config.yml:/etc/loki/local-config.yml   
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - my_network

  promtail:
    image: grafana/promtail:2.9.2
    container_name: promtail-flamingo
    volumes:
      - /var/log:/var/log
      - /home/umut/Doflamingo/promtail-config.yml:/etc/promtail/promtail-config.yml  
    command: -config.file=/etc/promtail/config.yml
    networks:
      - my_network
    

volumes:
  db:
  grafana-data: